INSERT INTO category (name) VALUES
  ('Other'),
  ('Artificial intelligence'),
  ('Education'),
  ('Marketing'),
  ('IT'),
  ('Finance'),
  ('E-commerce'),
  ('Consulting'),
  ('Design'),
  ('Health'),
  ('Wellness'),
  ('Fitness'),
  ('Fashion'),
  ('SaaS'),
  ('Social media'),
  ('Music'),
  ('Fintech & Banking'),
  ('Healthcare'),
  ('Agriculture'),
  ('Energy'),
  ('Retail'),
  ('Entertainment'),
  ('Media'),
  ('Transportation'),
  ('Real estate'),
  ('Food and beverage'),
  ('Consumer goods'),
  ('Social impact'),
  ('Arts and culture'),
  ('Sports'),
  ('Public services'),
  ('Tourism'),
  ('Gaming'),
  ('Safety'),
  ('Legal'),
  ('Human resources'),
  ('Construction'),
  ('Telecommunications'),
  ('Automotive'),
  ('Logistics'),
  ('Hospitality'),
  ('Enterprise solutions'),
  ('Beauty'),
  ('Events'),
  ('Farming'),
  ('Utilities'),
  ('Web development');
